package pl.luckboy.combirian.interp

object BuiltinFunction extends Enumeration 
{
  val Neg = Value("-")
  val Add = Value("#+")
  val Sub = Value("#-")
  val Mul = Value("#*")
  val Div = Value("#/")
  val Mod = Value("#%")
  val Not = Value("~") 
  val And = Value("#&")
  val Or = Value("#|")
  val Xor = Value("#^")
  val LeftShift = Value("#<<")
  val RightShift = Value("#>>")
  val Eq = Value("#==")
  val NotEq = Value("#!=")
  val Lt = Value("#<")
  val Le = Value("#<=")
  val Gt = Value("#>")
  val Ge = Value("#>=")
  val Cond = Value("cond")
  val Vector = Value("vector")
  val Map = Value("map")
  val Array = Value("array")
  val Hash = Value("hash")
  val Size = Value("size")
  val Haskey = Value("haskey")
  val Keys = Value("keys")
  val Keyarray = Value("keyarray")
  val Nth = Value("nth")
  val Updated = Value("updated")
  val Istypeof = Value("istypeof")
  val Intfrom = Value("intfrom")
  val Floatfrom = Value("floatfrom")
  val Vectorfrom = Value("vectorfrom")
  val Mapfrom = Value("hashfrom")
  val Arrayfrom = Value("arrayfrom")
  val Hashfrom = Value("hashfrom")
  val Size2 = Value("size2")
  val Haskey2 = Value("haskey2")
  val Keys2 = Value("keys2")
  val Keyarray2 = Value("keyarray2")
  val Nth2 = Value("nth2")
}