package pl.luckboy.combirian.interp

object BuiltinFunction extends Enumeration 
{
  val Neg = Value("-")
  val Add = Value("#+")
  val Sub = Value("#-")
  val Mul = Value("#*")
  val Div = Value("#/")
  val Mod = Value("#%")
  val Not = Value("~") 
  val And = Value("#&")
  val Or = Value("#|")
  val Xor = Value("#^")
  val LeftShift = Value("#<<")
  val RightShift = Value("#>>")
  val Eq = Value("#==")
  val NotEq = Value("#!=")
  val Lt = Value("#<")
  val Le = Value("#<=")
  val Gt = Value("#>")
  val Ge = Value("#>=")
  val Cons = Value("#::")
  val Cond = Value("cond")
  val Array = Value("array")
  val Length = Value("length")
  val Contains = Value("contains")
  val Nth = Value("nth")
  val Updated = Value("updated")
  val Istypeof = Value("istypeof")
}